### ISSUE TITLE
Further datetime issues in Python 3.8+

### ISSUE THREAD

**Issue by nathanjrobertson** [renalreg/PyXB-X#8]
I've had a look through the repo, and see some fixes for the datetime changes in Python 3.8+. I have a test case below which passes in Python 3.7 (both PyXB and PyXB-X), but fails on Python 3.8+ with PyXB-X.

https://github.com/nathanjrobertson/PyXB-X-datetime-testcase

It seems that adding a dateutil.relativedelta.relativedelta to a PyXB date object triggers the issue, like [this case here](https://github.com/nathanjrobertson/PyXB-X-datetime-testcase/blob/a9f5eaab59a4e02c573a3b007b3381cd57f5061a/test.py#L17).

There is also some debug being put out to stdout by PyXB-X just before the crash, so I'm assuming that's debugging that was accidentally left in the code, which incidentally is probably the code that has the bug this test case is triggering.

The README.md in the above repo includes all the output from the test case on all of Python 3.7-3.10, but the short version is:

```
pyxbx-datetime-bug-pyxbtest-1  | Traceback (most recent call last):
pyxbx-datetime-bug-pyxbtest-1  |   File "test.py", line 17, in <module>
pyxbx-datetime-bug-pyxbtest-1  |     period.twoDate = period.oneDate + relativedelta(days = -3)
pyxbx-datetime-bug-pyxbtest-1  |   File "/usr/local/lib/python3.8/site-packages/dateutil/relativedelta.py", line 405, in __radd__
pyxbx-datetime-bug-pyxbtest-1  |     return self.__add__(other)
pyxbx-datetime-bug-pyxbtest-1  |   File "/usr/local/lib/python3.8/site-packages/dateutil/relativedelta.py", line 387, in __add__
pyxbx-datetime-bug-pyxbtest-1  |     ret = (other.replace(**repl)
pyxbx-datetime-bug-pyxbtest-1  |   File "/usr/local/lib/python3.8/site-packages/pyxb/binding/datatypes.py", line 687, in __new__
pyxbx-datetime-bug-pyxbtest-1  |     raise TypeError('function takes %d arguments plus optional tzinfo (%d given)' % (len(cls._ValidFields), len(args)))
pyxbx-datetime-bug-pyxbtest-1  | TypeError: function takes 3 arguments plus optional tzinfo (8 given)
pyxbx-datetime-bug-pyxbtest-1 exited with code 1
```

Where period is an instance of a class generated by pybxgen (hence uses the PyXB datetime code).

@jtc42 Going through the GitHub logs, it looks like you worked on this recently. Would you mind taking a look at the above test case? Thank you.

**Comment by jtc42** [comment]
Hey thanks for the info. I'll try and get round to taking a look at some point, but I'm currently busy enough that it may be a while yet. In the meantime, if you manage to find a workaround or a fix I'm more than happy to take pull requests and I'll push out a new release ASAP.

**Comment by nathanjrobertson** [comment]
@jtc42 I've opened a pull request which resolves this issue. If you could review, and if accepted, make a release, that would be fantastic. Thanks.

**Comment by jtc42** [comment]
Thanks. PR has been merged and I'll try and sort out a release now.

**Comment by jtc42** [comment]
Now release, please install with `pip install PyXB-X==1.2.6.1`. Please see notes on the slightly odd versioning here https://github.com/renalreg/PyXB-X/blob/master/README.md#versioning
